apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "first-subscriber-api.fullname" . }}
  labels:
    {{- include "first-subscriber-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "first-subscriber-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "first-subscriber-api.selectorLabels" . | nindent 8 }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: {{ .Chart.Name | quote }}
        dapr.io/port: "80"
        dapr.io/config: "tracing"
        dapr.io/log-level: "debug"  
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: ASPNETCORE__ENVIRONMENT
            value: "Production"